### ISSUE TITLE
possible error in tps or inverse function?

### ISSUE THREAD

**Issue by derMart** [tilemapjp/ThinPlateSplineJS#1]
Here is a (real world) example with 23 control points, where either the forward or the backward or both are not correct. Consider the control points and the code in this gist:
https://gist.github.com/derMart/cc0690d01d6e34eed9df44ef6fc21e81#file-gistfile1-txt

The output is as follows:
[0, 3.203753652853152, 0, 16.575001528673965]
[640, 608.3312600256714, 0, 13.1385404900999]
[0, 14.086729548932908, 520, 510.3458485272256]
[640, 634.8386526228645, 520, 506.0523689941971]

This means, projecting point [0,0] forward and then again backward through the tps gives the point [3.2, 16.6] which is far off....

Anybody got an explanation for this?

best

**Comment by kochizufan** [comment]
Hi derMart,

Unfortunately ThinPlateSplineJS never guarantee round trip transformation.

If you want to have transforming solution which guarantee bijective transformation,
I have another project
https://github.com/code4nara/Maplat/
And you can use this library
https://github.com/code4nara/Maplat/blob/master/js/tin.js

I will create some sample of using this library on jsfiddle, please give me couple of days.

BR,
Kohei aka kochizufan

**Comment by kochizufan** [comment]
I made new JavaScript library distribution:
https://raw.githubusercontent.com/code4nara/Maplat/master/dist/maplat_tin.js

You can use it like this:
https://jsfiddle.net/kochizufan/gasyj62p/

The result is:
[
  [0, 0, 0, -7.105427357601002e-15],
  [640, 640.0000000000001, 0, 1.4210854715202004e-14],
  [0, 1.4210854715202004e-14, 520, 520.0000000000001],
  [640, 640, 520, 520]
]
Unfortunately there are some subtle mismatch because of rounding error, but you can ignore it by using Math.round or so.

**Comment by derMart** [comment]
Thank you very much! This is great work. I will experiment with the library. I am using this for an academic visualization project. It is about visualizing the transformations of warped maps. Therefore I preferable need a projection where also the inversion is implementable. Ironically gdalwarp is doing the same I did where I discovered the problem (see https://trac.osgeo.org/gdal/ticket/2630#comment:3 ). They discovered it 10 years ago. Would also be interesting to see if they fixed it...but I guess I know the answer ;-)
Ideally I also want to visualize tps as it is used by many projects. So I will also have a look how your warping compares to tps. Have you published this work as a paper, or is there any citable thing which explains the concept behind? If I use it (of course I'll only do if your license allows) I'd love to credit this appropriately. best

**Comment by kochizufan** [comment]
The deck explaining my logic can be found on https://www.slideshare.net/kokogiko/maplat (Sorry only in Japanese). You can imagine the logic by reading page 44 ( https://www.slideshare.net/kokogiko/maplat/44 ) to page 47.
My project main site is https://github.com/code4nara/Maplat/wiki
And I am now claiming Japan patent for this logic, claiming number is Japan Patent Claiming 2017-218223. (Don't worry, using this open source library is eternally free)
If you want to cite my library, please cite to one or some of these resources.

BR,
Kohei

**Comment by kochizufan** [comment]
Hi @derMart 

Do you use new logic js on Node.js? or on Browser?

If on browser, using
https://raw.githubusercontent.com/code4nara/Maplat/master/dist/maplat_tin.js
is OK, it works same like https://jsfiddle.net/kochizufan/gasyj62p/ .

But if you want to use it on Node.js, you should use 
https://raw.githubusercontent.com/code4nara/Maplat/master/js/tin.js
and prerequisite node modules are:
* npm install --save-dev @turf/turf@5.1.6
* npm install --save-dev mapshaper@0.4.31
After install them, you can use this library in Node.js by "var Tin = require(./tin);"
